import os


IBM_QUANTUM_TOKEN = os.getenv("IBM_QUANTUM_TOKEN", "")
IBM_QUANTUM_INSTANCE = os.getenv("IBM_QUANTUM_INSTANCE", "")
IBM_QUANTUM_CHANNEL = os.getenv("IBM_QUANTUM_CHANNEL", "ibm_quantum_platform")
IBM_QUANTUM_BACKEND = os.getenv("IBM_QUANTUM_BACKEND", "ibm_torino")

MAX_QUBITS = 127
DEFAULT_RISK_FACTOR = 0.5
DEFAULT_BUDGET_RATIO = 0.5
QAOA_REPS = 3
QAOA_MAX_ITER = 250
MONTE_CARLO_SHOTS = 10000
